### ISSUE TITLE
colab installation fails on cuda 12.2 

### ISSUE THREAD

**Issue by helloworld53** [casper-hansen/AutoAWQ_kernels#13]
![image](https://github.com/casper-hansen/AutoAWQ_kernels/assets/97686596/fd712847-c6da-42b5-932b-aff0921eeeb2)
The latest wheels are for 12.1 , would that be the issue?

**Comment by Boltuzamaki** [comment]
Hey I fixed this issue just now , so current autoawq-kernels build on CUDA 12.1.1 as mentioned in repo

In colab we have 

`
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0
`

So you need to build from source using 
`
!git clone https://github.com/casper-hansen/AutoAWQ_kernels
cd AutoAWQ_kernels
!pip install -e .
`

or you can use
 
https://github.com/Boltuzamaki/AutoAWQ_kernels

I build and saved it in builds folder you can just do pip install using this wheel. As this was taking a lot of time to build on colab everytime

**Comment by helloworld53** [comment]
thank you for the wheels !
