### ISSUE TITLE
auto-awq kernels is needed to be installed to use `.backward()`

### ISSUE THREAD

**Issue by webwlsong** [casper-hansen/AutoAWQ_kernels#19]
env :
python : 3.9.18
CUDA:Cuda compilation tools, release 12.1, V12.1.105
autoawq                           0.2.5
autoawq_kernels                   0.0.6

model: Qwen2-72B-Instruct-AWQ

error:
ValueError: auto-awq kernels is needed to be installed to use `.backward()`. Make sure to install the auto-awq kernels by following the installation guides in https://github.com/casper-hansen/AutoAWQ_kernels

**Comment by casper-hansen** [comment]
Hi @webwlsong, maybe the installation didn't go as expected. Can you try the following command and paste the output?

`pip install -v autoawq-kernels`

**Comment by webwlsong** [comment]
HI @casper-hansen    pip install -v autoawq-kernels  

result:
Using pip 24.0 from /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages/pip (python 3.9)
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: autoawq_kernels in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (0.0.6)
Requirement already satisfied: torch>=2.0.1 in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from autoawq_kernels) (2.3.0)
Requirement already satisfied: filelock in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from torch>=2.0.1->autoawq_kernels) (3.13.4)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from torch>=2.0.1->autoawq_kernels) (4.12.2)
Requirement already satisfied: sympy in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from torch>=2.0.1->autoawq_kernels) (1.12.1)
Requirement already satisfied: networkx in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from torch>=2.0.1->autoawq_kernels) (3.2.1)
Requirement already satisfied: jinja2 in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from torch>=2.0.1->autoawq_kernels) (3.1.4)
Requirement already satisfied: fsspec in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from torch>=2.0.1->autoawq_kernels) (2024.2.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from torch>=2.0.1->autoawq_kernels) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from torch>=2.0.1->autoawq_kernels) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from torch>=2.0.1->autoawq_kernels) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from torch>=2.0.1->autoawq_kernels) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from torch>=2.0.1->autoawq_kernels) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from torch>=2.0.1->autoawq_kernels) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from torch>=2.0.1->autoawq_kernels) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from torch>=2.0.1->autoawq_kernels) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from torch>=2.0.1->autoawq_kernels) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5 in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from torch>=2.0.1->autoawq_kernels) (2.20.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from torch>=2.0.1->autoawq_kernels) (12.1.105)
Requirement already satisfied: triton==2.3.0 in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from torch>=2.0.1->autoawq_kernels) (2.3.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=2.0.1->autoawq_kernels) (12.5.40)
Requirement already satisfied: MarkupSafe>=2.0 in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from jinja2->torch>=2.0.1->autoawq_kernels) (2.1.5)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in /home/zmyl/anaconda3/envs/zmyl39/lib/python3.9/site-packages (from sympy->torch>=2.0.1->autoawq_kernels) (1.3.0)

**Comment by webwlsong** [comment]
Package                           Version
--------------------------------- ------------
accelerate                        0.31.0
addict                            2.4.0
aiofiles                          23.2.1
aiohttp                           3.9.5
aiosignal                         1.3.1
aliyun-python-sdk-core            2.15.1
aliyun-python-sdk-kms             2.16.3
altair                            5.3.0
annotated-types                   0.7.0
anyio                             4.4.0
async-timeout                     4.0.3
attrs                             23.2.0
auto_gptq                         0.7.1
autoawq                           0.2.5
autoawq_kernels                   0.0.6
bitsandbytes                      0.42.0
blinker                           1.8.2
Brotli                            1.1.0
cachetools                        5.3.3
certifi                           2024.6.2
cffi                              1.16.0
charset-normalizer                3.3.2
click                             8.1.7
cloudpickle                       3.0.0
cmake                             3.29.5
colorama                          0.4.6
coloredlogs                       15.0.1
contourpy                         1.2.1
crcmod                            1.7
cryptography                      42.0.8
cycler                            0.12.1
datasets                          2.18.0
deepspeed                         0.14.2
dill                              0.3.8
diskcache                         5.6.3
distro                            1.9.0
dnspython                         2.6.1
docstring_parser                  0.16
einops                            0.8.0
email_validator                   2.1.1
eval_type_backport                0.2.0
exceptiongroup                    1.2.1
fastapi                           0.111.0
fastapi-cli                       0.0.4
ffmpy                             0.3.2
filelock                          3.13.4
fire                              0.6.0
fonttools                         4.53.0
frozenlist                        1.4.1
fsspec                            2024.2.0
gast                              0.5.4
gekko                             1.1.1
gitdb                             4.0.11
GitPython                         3.1.43
gmpy2                             2.1.5
gradio                            4.36.1
gradio_client                     1.0.1
h11                               0.14.0
hf_transfer                       0.1.6
hjson                             3.1.0
httpcore                          1.0.5
httptools                         0.6.1
httpx                             0.27.0
huggingface-hub                   0.23.3
humanfriendly                     10.0
idna                              3.7
importlib_metadata                7.1.0
importlib_resources               6.4.0
intel-openmp                      2024.1.2
interegular                       0.3.3
Jinja2                            3.1.4
jiwer                             3.0.4
jmespath                          0.10.0
joblib                            1.4.2
jsonschema                        4.22.0
jsonschema-specifications         2023.12.1
kiwisolver                        1.4.5
lark                              1.1.9
llamafactory                      0.8.1
llmtuner                          0.7.1
llvmlite                          0.42.0
lm-format-enforcer                0.10.1
lxml                              5.2.2
markdown-it-py                    3.0.0
MarkupSafe                        2.1.5
matplotlib                        3.9.0
mdurl                             0.1.2
mkl                               2024.1.0
mkl-service                       2.4.1
modelscope                        1.15.0
mpmath                            1.3.0
msgpack                           1.0.8
multidict                         6.0.5
multiprocess                      0.70.16
nest-asyncio                      1.6.0
networkx                          3.2.1
ninja                             1.11.1.1
numba                             0.59.1
numpy                             1.26.4
nvidia-cublas-cu12                12.1.3.1
nvidia-cuda-cupti-cu12            12.1.105
nvidia-cuda-nvrtc-cu12            12.1.105
nvidia-cuda-runtime-cu12          12.1.105
nvidia-cudnn-cu12                 8.9.2.26
nvidia-cufft-cu12                 11.0.2.54
nvidia-curand-cu12                10.3.2.106
nvidia-cusolver-cu12              11.4.5.107
nvidia-cusparse-cu12              12.1.0.106
nvidia-ml-py                      12.555.43
nvidia-nccl-cu12                  2.20.5
nvidia-nvjitlink-cu12             12.5.40
nvidia-nvtx-cu12                  12.1.105
openai                            1.33.0
optimum                           1.20.0
orjson                            3.10.4
oss2                              2.18.5
outlines                          0.0.34
overrides                         7.7.0
packaging                         24.1
pandas                            2.2.2
peft                              0.11.1
pillow                            10.3.0
pip                               24.0
pip-review                        1.3.0
platformdirs                      4.2.2
portalocker                       2.8.2
prometheus_client                 0.20.0
prometheus-fastapi-instrumentator 7.0.0
protobuf                          5.27.0
psutil                            5.9.8
py-cpuinfo                        9.0.0
pyairports                        2.1.1
pyarrow                           16.1.0
pyarrow-hotfix                    0.6
pycountry                         24.6.1
pycparser                         2.22
pycryptodome                      3.20.0
pydantic                          2.7.3
pydantic_core                     2.18.4
pydeck                            0.9.1
pydub                             0.25.1
Pygments                          2.18.0
Pympler                           1.0.1
pynvml                            11.5.0
pyparsing                         3.1.2
python-dateutil                   2.9.0.post0
python-dotenv                     1.0.1
python-multipart                  0.0.9
pytz                              2024.1
PyYAML                            6.0.1
rapidfuzz                         3.9.3
ray                               2.24.0
referencing                       0.35.1
regex                             2024.5.15
requests                          2.32.3
rich                              13.7.1
rouge                             1.0.1
rpds-py                           0.18.1
ruff                              0.4.8
sacrebleu                         2.4.2
safetensors                       0.4.3
scipy                             1.13.1
semantic-version                  2.10.0
semver                            3.0.2
sentencepiece                     0.2.0
setuptools                        69.5.1
shellingham                       1.5.4
shtab                             1.7.1
simplejson                        3.19.2
six                               1.16.0
smmap                             5.0.1
sniffio                           1.3.1
sortedcontainers                  2.4.0
sse-starlette                     2.1.0
starlette                         0.37.2
streamlit                         1.8.0
sympy                             1.12.1
tabulate                          0.9.0
tbb                               2021.12.0
tenacity                          8.3.0
termcolor                         2.4.0
tiktoken                          0.6.0
tokenizers                        0.19.1
toml                              0.10.2
tomli                             2.0.1
tomlkit                           0.12.0
toolz                             0.12.1
torch                             2.3.0
torcheval                         0.0.7
tornado                           6.4.1
tqdm                              4.66.4
transformers                      4.41.2
triton                            2.3.0
trl                               0.9.4
typer                             0.12.3
typing_extensions                 4.12.2
tyro                              0.8.4
tzdata                            2024.1
tzlocal                           5.2
ujson                             5.10.0
urllib3                           2.2.1
uvicorn                           0.30.1
uvloop                            0.19.0
validators                        0.28.3
vllm                              0.4.3
vllm-flash-attn                   2.5.8.post2
watchdog                          4.0.1
watchfiles                        0.22.0
websockets                        11.0.3
wheel                             0.43.0
xformers                          0.0.26.post1
xxhash                            3.4.1
yapf                              0.40.2
yarl                              1.9.4
zipp                              3.19.2
zstandard                         0.22.0




error:
ValueError: auto-awq kernels is needed to be installed to use `.backward()`. Make sure to install the auto-awq kernels by following the installation guides in [GitHub - casper-hansen/AutoAWQ_kernels](https://github.com/casper-hansen/AutoAWQ_kernels)

**Comment by jyrana** [comment]
did you find any solution? I ran into the same issue.

**Comment by webwlsong** [comment]
@jyrana 

Uninstalling autoawq kernels and installing it using source code resulted in system errors.
My system is Centos7, and an error occurred during the source code installation, indicating that the gcc version is too low, resulting in upgrading to the gcc++version. That's it.

**Comment by jyrana** [comment]
can you tell me which version of GCC did you use? I have gcc 13.1 and  pip install -e . is not getting executed, it stops at   Running setup.py develop for autoawq_kernels..
