### ISSUE TITLE
Installation of AutoAWQ_kernels

### ISSUE THREAD

**Issue by jyrana** [casper-hansen/AutoAWQ_kernels#20]
I am using runpod torch2.2.0 image. I don't think AutoAWQ is getting installed properly.

Here's what's happening when Iam trying to install it from source.

root@30b7de36438a:/workspace/AutoAWQ_kernels# pip install -e .
Obtaining file:///workspace/AutoAWQ_kernels
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch>=2.0.1 in /usr/local/lib/python3.10/dist-packages (from autoawq_kernels==0.0.6+cu121) (2.2.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (4.9.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (1.12)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (3.2.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (3.1.3)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (2024.2.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (2.19.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (12.1.105)
Requirement already satisfied: triton==2.2.0 in /usr/local/lib/python3.10/dist-packages (from torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (2.2.0)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.10/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (12.3.101)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=2.0.1->autoawq_kernels==0.0.6+cu121) (1.3.0)
Installing collected packages: autoawq_kernels
  Running setup.py develop for autoawq_kernels

It basically stops after running setup,py develop for autoawq_kernels. It's like this for 15-20 mins. I tried upgrading g++ version and it's giving me version not compatible error. can you tell me what should I do?

**Comment by casper-hansen** [comment]
Please uninstall autoawq kernels and run `pip install -v autoawq_kernels`. It should enable you to see what's happening. I personally use RunPod too on torch 2.2 and it has worked for me.
