### ISSUE TITLE
pls public autoawq_kernels v0.0.3 cuda 12.1 on windows

### ISSUE THREAD

**Issue by linhcentrio** [casper-hansen/AutoAWQ_kernels#7]
![image](https://github.com/casper-hansen/AutoAWQ_kernels/assets/45778128/f5ca182d-7798-463a-ba67-b62b9b97bcd9)
https://github.com/h2oai/h2ogpt/issues/1383

**Comment by casper-hansen** [comment]
Hi @linhcentrio, next release will build upon torch 2.2.0 and have wheels for CUDA 11.8 and 12.1.

**Comment by casper-hansen** [comment]
Made new releases. The CUDA 11.8 wheel is with torch 2.0.1 and the wheel you can get from pypi is with CUDA 12.1 and torch 2.2.0
